/* Generated by           cobc 2.0.0 */
/* Generated from         money_counter.cbl */
/* Generated at           Mar 03 2020 21:58:02 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -x -o bin\money_counter.exe -std=default -Wall -debug -g -free money_counter.cbl */

/* Program local variables for 'money_counter' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d0;
cob_decimal	*d1;


/* Screens */

static cob_screen	s_50;
static cob_screen	s_49;
static cob_screen	s_48;
static cob_screen	s_47;
static cob_screen	s_46;
static cob_screen	s_45;
static cob_screen	s_44;
static cob_screen	s_43;
static cob_screen	s_42;
static cob_screen	s_41;
static cob_screen	s_40;
static cob_screen	s_39;
static cob_screen	s_38;
static cob_screen	s_37;
static cob_screen	s_36;
static cob_screen	s_35;
static cob_screen	s_34;
static cob_screen	s_33;
static cob_screen	s_32;
static cob_screen	s_31;
static cob_screen	s_30;
static cob_screen	s_29;
static cob_screen	s_28;
static cob_screen	s_27;
static cob_screen	s_26;
static cob_screen	s_25;
static cob_screen	s_24;
static cob_screen	s_23;
static cob_screen	s_22;
static cob_screen	s_21;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_1;	/* RETURN-CODE */
static cob_u8_t	b_6[8] __attribute__((aligned));	/* penny_rolls */
static cob_u8_t	b_7[8] __attribute__((aligned));	/* nickel_rolls */
static cob_u8_t	b_8[8] __attribute__((aligned));	/* dime_rolls */
static cob_u8_t	b_9[8] __attribute__((aligned));	/* quarter_rolls */
static cob_u8_t	b_10[8] __attribute__((aligned));	/* half_rolls */
static cob_u8_t	b_11[8] __attribute__((aligned));	/* ones */
static cob_u8_t	b_12[8] __attribute__((aligned));	/* twos */
static cob_u8_t	b_13[8] __attribute__((aligned));	/* fives */
static cob_u8_t	b_14[8] __attribute__((aligned));	/* tens */
static cob_u8_t	b_15[8] __attribute__((aligned));	/* twenties */
static cob_u8_t	b_16[8] __attribute__((aligned));	/* fifties */
static cob_u8_t	b_17[8] __attribute__((aligned));	/* hundreds */
static cob_u8_t	b_18[8] __attribute__((aligned));	/* estimated_change */
static cob_u8_t	b_19[11] __attribute__((aligned));	/* calc */
static cob_u8_t	b_20[11] __attribute__((aligned));	/* total */
static cob_u8_t	b_21[273] __attribute__((aligned));	/* detail-screen */
static cob_u8_t	b_51[4] __attribute__((aligned));	/* COB-CRT-STATUS */

/* End of data storage */


/* Fields */
static cob_field f_6	= {8, b_6, &a_3};	/* penny_rolls */
static cob_field f_7	= {8, b_7, &a_3};	/* nickel_rolls */
static cob_field f_8	= {8, b_8, &a_3};	/* dime_rolls */
static cob_field f_9	= {8, b_9, &a_3};	/* quarter_rolls */
static cob_field f_10	= {8, b_10, &a_3};	/* half_rolls */
static cob_field f_11	= {8, b_11, &a_3};	/* ones */
static cob_field f_12	= {8, b_12, &a_3};	/* twos */
static cob_field f_13	= {8, b_13, &a_3};	/* fives */
static cob_field f_14	= {8, b_14, &a_3};	/* tens */
static cob_field f_15	= {8, b_15, &a_3};	/* twenties */
static cob_field f_16	= {8, b_16, &a_3};	/* fifties */
static cob_field f_17	= {8, b_17, &a_3};	/* hundreds */
static cob_field f_18	= {8, b_18, &a_3};	/* estimated_change */
static cob_field f_19	= {11, b_19, &a_1};	/* calc */
static cob_field f_20	= {11, b_20, &a_1};	/* total */
static cob_field f_21	= {273, b_21, &a_4};	/* detail-screen */
static cob_field f_22	= {13, b_21, &a_2};	/* Implicit FILLER */
static cob_field f_23	= {13, b_21 + 13, &a_2};	/* Implicit FILLER */
static cob_field f_24	= {8, b_21 + 26, &a_2};	/* penny_roll_field */
static cob_field f_25	= {14, b_21 + 34, &a_2};	/* Implicit FILLER */
static cob_field f_26	= {8, b_21 + 48, &a_2};	/* nickel_roll_field */
static cob_field f_27	= {12, b_21 + 56, &a_2};	/* Implicit FILLER */
static cob_field f_28	= {8, b_21 + 68, &a_2};	/* dime_roll_field */
static cob_field f_29	= {15, b_21 + 76, &a_2};	/* Implicit FILLER */
static cob_field f_30	= {8, b_21 + 91, &a_2};	/* quarter_roll_field */
static cob_field f_31	= {12, b_21 + 99, &a_2};	/* Implicit FILLER */
static cob_field f_32	= {8, b_21 + 111, &a_2};	/* half_roll_field */
static cob_field f_33	= {6, b_21 + 119, &a_2};	/* Implicit FILLER */
static cob_field f_34	= {8, b_21 + 125, &a_2};	/* ones_field */
static cob_field f_35	= {6, b_21 + 133, &a_2};	/* Implicit FILLER */
static cob_field f_36	= {8, b_21 + 139, &a_2};	/* twos_field */
static cob_field f_37	= {7, b_21 + 147, &a_2};	/* Implicit FILLER */
static cob_field f_38	= {8, b_21 + 154, &a_2};	/* fives_field */
static cob_field f_39	= {6, b_21 + 162, &a_2};	/* Implicit FILLER */
static cob_field f_40	= {8, b_21 + 168, &a_2};	/* tens_field */
static cob_field f_41	= {10, b_21 + 176, &a_2};	/* Implicit FILLER */
static cob_field f_42	= {8, b_21 + 186, &a_2};	/* twenties_field */
static cob_field f_43	= {9, b_21 + 194, &a_2};	/* Implicit FILLER */
static cob_field f_44	= {8, b_21 + 203, &a_2};	/* fifties_field */
static cob_field f_45	= {10, b_21 + 211, &a_2};	/* Implicit FILLER */
static cob_field f_46	= {8, b_21 + 221, &a_2};	/* hundreds_field */
static cob_field f_47	= {18, b_21 + 229, &a_2};	/* Implicit FILLER */
static cob_field f_48	= {8, b_21 + 247, &a_2};	/* estimated_change_field */
static cob_field f_49	= {7, b_21 + 255, &a_2};	/* Implicit FILLER */
static cob_field f_50	= {11, b_21 + 262, &a_2};	/* total_field */
static cob_field f_51	= {4, b_51, &a_8};	/* COB-CRT-STATUS */

/* End of fields */

