/* Generated by           cobc 2.0.0 */
/* Generated from         money_counter.cbl */
/* Generated at           Mar 03 2020 21:58:02 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        cobc.exe -x -o bin\money_counter.exe -std=default -Wall -debug -g -free money_counter.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"money_counter.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Mar 03 2020 21:58:02"
#define  COB_MODULE_DATE		20200303
#define  COB_MODULE_TIME		215802

/* Global variables */
#include "money_counter.c.h"

/* Function prototypes */

static int		money_counter ();
static int		money_counter_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (money_counter ());
}

/* Functions */

/* PROGRAM-ID 'money_counter' */

/* ENTRY 'money_counter' */

static int
money_counter ()
{
  return money_counter_ (0);
}

static int
money_counter_ (const int entry)
{
  /* Program local variables */
  #include "money_counter.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d0, &d1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 79        : Entry     money_counter           : money_counter.cbl */
  l_2:;
  cob_trace_section (st_2, st_1, 79);
  cob_trace_section (st_3, st_1, 79);

  /* Line: 79        : Paragraph MAIN                    : money_counter.cbl */
  cob_trace_section (st_4, st_1, 79);

  /* Line: 80        : GO TO              : money_counter.cbl */
  cob_set_location (st_1, 80, NULL, st_5, st_6);
  goto l_5;

  /* Line: 81        : STOP RUN           : money_counter.cbl */
  cob_set_location (st_1, 81, NULL, st_5, st_7);
  cob_stop_run (b_1);

  /* Line: 83        : Paragraph MAIN_LOOP               : money_counter.cbl */
  l_5:;
  cob_trace_section (st_8, st_1, 83);

  /* Line: 84        : ACCEPT             : money_counter.cbl */
  cob_set_location (st_1, 84, NULL, st_9, st_10);
  cob_move (&f_20, &f_50);
  cob_move (&f_18, &f_48);
  cob_move (&f_17, &f_46);
  cob_move (&f_16, &f_44);
  cob_move (&f_15, &f_42);
  cob_move (&f_14, &f_40);
  cob_move (&f_13, &f_38);
  cob_move (&f_12, &f_36);
  cob_move (&f_11, &f_34);
  cob_move (&f_10, &f_32);
  cob_move (&f_9, &f_30);
  cob_move (&f_8, &f_28);
  cob_move (&f_7, &f_26);
  cob_move (&f_6, &f_24);
  cob_screen_accept (&s_21, NULL, NULL, NULL, 1);
  cob_move (&f_50, &f_20);
  cob_move (&f_48, &f_18);
  cob_move (&f_46, &f_17);
  cob_move (&f_44, &f_16);
  cob_move (&f_42, &f_15);
  cob_move (&f_40, &f_14);
  cob_move (&f_38, &f_13);
  cob_move (&f_36, &f_12);
  cob_move (&f_34, &f_11);
  cob_move (&f_32, &f_10);
  cob_move (&f_30, &f_9);
  cob_move (&f_28, &f_8);
  cob_move (&f_26, &f_7);
  cob_move (&f_24, &f_6);

  /* Line: 85        : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 85, NULL, st_9, st_11);
  cob_move ((cob_field *)&c_1, &f_19);

  /* Line: 86        : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 86, NULL, st_9, st_11);
  cob_move ((cob_field *)&c_1, &f_20);

  /* Line: 88        : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 88, NULL, st_9, st_11);
  cob_move (&f_24, &f_6);

  /* Line: 90        : MULTIPLY           : money_counter.cbl */
  cob_set_location (st_1, 90, NULL, st_9, st_12);
  cob_decimal_set_field (d0, (cob_field *)&c_2);
  cob_decimal_set_field (d1, &f_6);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_19, 0);

  /* Line: 91        : ADD                : money_counter.cbl */
  cob_set_location (st_1, 91, NULL, st_9, st_13);
  cob_check_numeric (&f_19, "calc");
  cob_check_numeric (&f_20, "total");
  cob_add (&f_20, &f_19, 0);

  /* Line: 93        : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 93, NULL, st_9, st_11);
  cob_move (&f_26, &f_7);

  /* Line: 95        : MULTIPLY           : money_counter.cbl */
  cob_set_location (st_1, 95, NULL, st_9, st_12);
  cob_decimal_set_llint (d0, 2LL);
  cob_decimal_set_field (d1, &f_7);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_19, 0);

  /* Line: 96        : ADD                : money_counter.cbl */
  cob_set_location (st_1, 96, NULL, st_9, st_13);
  cob_check_numeric (&f_19, "calc");
  cob_check_numeric (&f_20, "total");
  cob_add (&f_20, &f_19, 0);

  /* Line: 98        : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 98, NULL, st_9, st_11);
  cob_move (&f_28, &f_8);

  /* Line: 100       : MULTIPLY           : money_counter.cbl */
  cob_set_location (st_1, 100, NULL, st_9, st_12);
  cob_decimal_set_llint (d0, 5LL);
  cob_decimal_set_field (d1, &f_8);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_19, 0);

  /* Line: 101       : ADD                : money_counter.cbl */
  cob_set_location (st_1, 101, NULL, st_9, st_13);
  cob_check_numeric (&f_19, "calc");
  cob_check_numeric (&f_20, "total");
  cob_add (&f_20, &f_19, 0);

  /* Line: 103       : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 103, NULL, st_9, st_11);
  cob_move (&f_30, &f_9);

  /* Line: 105       : MULTIPLY           : money_counter.cbl */
  cob_set_location (st_1, 105, NULL, st_9, st_12);
  cob_decimal_set_llint (d0, 10LL);
  cob_decimal_set_field (d1, &f_9);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_19, 0);

  /* Line: 106       : ADD                : money_counter.cbl */
  cob_set_location (st_1, 106, NULL, st_9, st_13);
  cob_check_numeric (&f_19, "calc");
  cob_check_numeric (&f_20, "total");
  cob_add (&f_20, &f_19, 0);

  /* Line: 108       : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 108, NULL, st_9, st_11);
  cob_move (&f_32, &f_10);

  /* Line: 110       : MULTIPLY           : money_counter.cbl */
  cob_set_location (st_1, 110, NULL, st_9, st_12);
  cob_decimal_set_llint (d0, 10LL);
  cob_decimal_set_field (d1, &f_10);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_19, 0);

  /* Line: 111       : ADD                : money_counter.cbl */
  cob_set_location (st_1, 111, NULL, st_9, st_13);
  cob_check_numeric (&f_19, "calc");
  cob_check_numeric (&f_20, "total");
  cob_add (&f_20, &f_19, 0);

  /* Line: 113       : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 113, NULL, st_9, st_11);
  cob_move (&f_34, &f_11);

  /* Line: 114       : ADD                : money_counter.cbl */
  cob_set_location (st_1, 114, NULL, st_9, st_13);
  cob_check_numeric (&f_20, "total");
  cob_add (&f_20, &f_11, 0);

  /* Line: 116       : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 116, NULL, st_9, st_11);
  cob_move (&f_36, &f_12);

  /* Line: 117       : MULTIPLY           : money_counter.cbl */
  cob_set_location (st_1, 117, NULL, st_9, st_12);
  cob_decimal_set_llint (d0, 2LL);
  cob_decimal_set_field (d1, &f_12);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_19, 0);

  /* Line: 118       : ADD                : money_counter.cbl */
  cob_set_location (st_1, 118, NULL, st_9, st_13);
  cob_check_numeric (&f_19, "calc");
  cob_check_numeric (&f_20, "total");
  cob_add (&f_20, &f_19, 0);

  /* Line: 120       : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 120, NULL, st_9, st_11);
  cob_move (&f_38, &f_13);

  /* Line: 121       : MULTIPLY           : money_counter.cbl */
  cob_set_location (st_1, 121, NULL, st_9, st_12);
  cob_decimal_set_llint (d0, 5LL);
  cob_decimal_set_field (d1, &f_13);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_19, 0);

  /* Line: 122       : ADD                : money_counter.cbl */
  cob_set_location (st_1, 122, NULL, st_9, st_13);
  cob_check_numeric (&f_19, "calc");
  cob_check_numeric (&f_20, "total");
  cob_add (&f_20, &f_19, 0);

  /* Line: 124       : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 124, NULL, st_9, st_11);
  cob_move (&f_40, &f_14);

  /* Line: 125       : MULTIPLY           : money_counter.cbl */
  cob_set_location (st_1, 125, NULL, st_9, st_12);
  cob_decimal_set_llint (d0, 10LL);
  cob_decimal_set_field (d1, &f_14);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_19, 0);

  /* Line: 126       : ADD                : money_counter.cbl */
  cob_set_location (st_1, 126, NULL, st_9, st_13);
  cob_check_numeric (&f_19, "calc");
  cob_check_numeric (&f_20, "total");
  cob_add (&f_20, &f_19, 0);

  /* Line: 128       : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 128, NULL, st_9, st_11);
  cob_move (&f_42, &f_15);

  /* Line: 129       : MULTIPLY           : money_counter.cbl */
  cob_set_location (st_1, 129, NULL, st_9, st_12);
  cob_decimal_set_llint (d0, 20LL);
  cob_decimal_set_field (d1, &f_15);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_19, 0);

  /* Line: 130       : ADD                : money_counter.cbl */
  cob_set_location (st_1, 130, NULL, st_9, st_13);
  cob_check_numeric (&f_19, "calc");
  cob_check_numeric (&f_20, "total");
  cob_add (&f_20, &f_19, 0);

  /* Line: 132       : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 132, NULL, st_9, st_11);
  cob_move (&f_44, &f_16);

  /* Line: 133       : MULTIPLY           : money_counter.cbl */
  cob_set_location (st_1, 133, NULL, st_9, st_12);
  cob_decimal_set_llint (d0, 50LL);
  cob_decimal_set_field (d1, &f_16);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_19, 0);

  /* Line: 134       : ADD                : money_counter.cbl */
  cob_set_location (st_1, 134, NULL, st_9, st_13);
  cob_check_numeric (&f_19, "calc");
  cob_check_numeric (&f_20, "total");
  cob_add (&f_20, &f_19, 0);

  /* Line: 136       : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 136, NULL, st_9, st_11);
  cob_move (&f_46, &f_17);

  /* Line: 137       : MULTIPLY           : money_counter.cbl */
  cob_set_location (st_1, 137, NULL, st_9, st_12);
  cob_decimal_set_llint (d0, 100LL);
  cob_decimal_set_field (d1, &f_17);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_19, 0);

  /* Line: 138       : ADD                : money_counter.cbl */
  cob_set_location (st_1, 138, NULL, st_9, st_13);
  cob_check_numeric (&f_19, "calc");
  cob_check_numeric (&f_20, "total");
  cob_add (&f_20, &f_19, 0);

  /* Line: 140       : MOVE               : money_counter.cbl */
  cob_set_location (st_1, 140, NULL, st_9, st_11);
  cob_move (&f_48, &f_18);

  /* Line: 142       : MULTIPLY           : money_counter.cbl */
  cob_set_location (st_1, 142, NULL, st_9, st_12);
  cob_decimal_set_field (d0, (cob_field *)&c_3);
  cob_decimal_set_field (d1, &f_18);
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, &f_19, 0);

  /* Line: 143       : ADD                : money_counter.cbl */
  cob_set_location (st_1, 143, NULL, st_9, st_13);
  cob_check_numeric (&f_19, "calc");
  cob_check_numeric (&f_20, "total");
  cob_add (&f_20, &f_19, 0);

  /* Line: 147       : GO TO              : money_counter.cbl */
  cob_set_location (st_1, 147, NULL, st_9, st_6);
  goto l_5;

  /* Line: 148       : STOP RUN           : money_counter.cbl */
  cob_set_location (st_1, 148, NULL, st_9, st_7);
  cob_stop_run (b_1);

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_section (st_14, NULL, 0);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_1;

  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  /* Initialize module structure */
  module->module_name = "money_counter";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())money_counter;
  module->module_cancel.funcptr = (void *(*)())money_counter_;
  module->collating_sequence = NULL;
  module->crt_status = &f_51;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_1 = 0;
  cob_move ((cob_field *)&c_1, &f_6);
  cob_move ((cob_field *)&c_1, &f_7);
  cob_move ((cob_field *)&c_1, &f_8);
  cob_move ((cob_field *)&c_1, &f_9);
  cob_move ((cob_field *)&c_1, &f_10);
  cob_move ((cob_field *)&c_1, &f_11);
  cob_move ((cob_field *)&c_1, &f_12);
  cob_move ((cob_field *)&c_1, &f_13);
  cob_move ((cob_field *)&c_1, &f_14);
  cob_move ((cob_field *)&c_1, &f_15);
  cob_move ((cob_field *)&c_1, &f_16);
  cob_move ((cob_field *)&c_1, &f_17);
  cob_move ((cob_field *)&c_1, &f_18);
  memset (b_19, 48, 11);
  memset (b_20, 48, 11);
  memset (b_51, 48, 4);

  /* Initialize SCREEN items */
  memcpy (b_21, "Money Counter", 13);
  memcpy (b_21 + 13, "Penny Rolls: ", 13);
  memset (b_21 + 26, 32, 8);
  memcpy (b_21 + 34, "Nickel Rolls: ", 14);
  memset (b_21 + 48, 32, 8);
  memcpy (b_21 + 56, "Dime Rolls: ", 12);
  memset (b_21 + 68, 32, 8);
  memcpy (b_21 + 76, "Quarter Rolls: ", 15);
  memset (b_21 + 91, 32, 8);
  memcpy (b_21 + 99, "Half Rolls: ", 12);
  memset (b_21 + 111, 32, 8);
  memcpy (b_21 + 119, "Ones: ", 6);
  memset (b_21 + 125, 32, 8);
  memcpy (b_21 + 133, "Twos: ", 6);
  memset (b_21 + 139, 32, 8);
  memcpy (b_21 + 147, "Fives: ", 7);
  memset (b_21 + 154, 32, 8);
  memcpy (b_21 + 162, "Tens: ", 6);
  memset (b_21 + 168, 32, 8);
  memcpy (b_21 + 176, "Twenties: ", 10);
  memset (b_21 + 186, 32, 8);
  memcpy (b_21 + 194, "Fifties: ", 9);
  memset (b_21 + 203, 32, 8);
  memcpy (b_21 + 211, "Hundreds: ", 10);
  memset (b_21 + 221, 32, 8);
  memcpy (b_21 + 229, "Estimated Change: ", 18);
  memset (b_21 + 247, 32, 8);
  memcpy (b_21 + 255, "Total: ", 7);
  memset (b_21 + 262, 32, 11);
  cob_set_screen (&s_21, NULL, NULL, 
  		  &s_22, NULL, NULL, 
  		  NULL, NULL, NULL, 
  		  NULL, NULL, NULL, 
  		  0, 0, 0x0);
  cob_set_screen (&s_22, &s_23, NULL, 
  		  NULL, &s_21, NULL, 
  		  &f_22, (cob_field *)&c_4, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_23, &s_24, &s_22, 
  		  NULL, &s_21, NULL, 
  		  &f_23, (cob_field *)&c_6, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_24, &s_25, &s_23, 
  		  NULL, &s_21, &f_24, 
  		  NULL, (cob_field *)&c_6, (cob_field *)&c_7, 
  		  NULL, NULL, NULL, 
  		  1, 0, 0x200000);
  cob_set_screen (&s_25, &s_26, &s_24, 
  		  NULL, &s_21, NULL, 
  		  &f_25, (cob_field *)&c_5, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_26, &s_27, &s_25, 
  		  NULL, &s_21, &f_26, 
  		  NULL, (cob_field *)&c_5, (cob_field *)&c_7, 
  		  NULL, NULL, NULL, 
  		  1, 0, 0x200000);
  cob_set_screen (&s_27, &s_28, &s_26, 
  		  NULL, &s_21, NULL, 
  		  &f_27, (cob_field *)&c_8, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_28, &s_29, &s_27, 
  		  NULL, &s_21, &f_28, 
  		  NULL, (cob_field *)&c_8, (cob_field *)&c_7, 
  		  NULL, NULL, NULL, 
  		  1, 0, 0x200000);
  cob_set_screen (&s_29, &s_30, &s_28, 
  		  NULL, &s_21, NULL, 
  		  &f_29, (cob_field *)&c_9, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_30, &s_31, &s_29, 
  		  NULL, &s_21, &f_30, 
  		  NULL, (cob_field *)&c_9, (cob_field *)&c_7, 
  		  NULL, NULL, NULL, 
  		  1, 0, 0x200000);
  cob_set_screen (&s_31, &s_32, &s_30, 
  		  NULL, &s_21, NULL, 
  		  &f_31, (cob_field *)&c_10, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_32, &s_33, &s_31, 
  		  NULL, &s_21, &f_32, 
  		  NULL, (cob_field *)&c_10, (cob_field *)&c_7, 
  		  NULL, NULL, NULL, 
  		  1, 0, 0x200000);
  cob_set_screen (&s_33, &s_34, &s_32, 
  		  NULL, &s_21, NULL, 
  		  &f_33, (cob_field *)&c_11, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_34, &s_35, &s_33, 
  		  NULL, &s_21, &f_34, 
  		  NULL, (cob_field *)&c_11, (cob_field *)&c_7, 
  		  NULL, NULL, NULL, 
  		  1, 0, 0x200000);
  cob_set_screen (&s_35, &s_36, &s_34, 
  		  NULL, &s_21, NULL, 
  		  &f_35, (cob_field *)&c_12, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_36, &s_37, &s_35, 
  		  NULL, &s_21, &f_36, 
  		  NULL, (cob_field *)&c_12, (cob_field *)&c_7, 
  		  NULL, NULL, NULL, 
  		  1, 0, 0x200000);
  cob_set_screen (&s_37, &s_38, &s_36, 
  		  NULL, &s_21, NULL, 
  		  &f_37, (cob_field *)&c_13, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_38, &s_39, &s_37, 
  		  NULL, &s_21, &f_38, 
  		  NULL, (cob_field *)&c_13, (cob_field *)&c_7, 
  		  NULL, NULL, NULL, 
  		  1, 0, 0x200000);
  cob_set_screen (&s_39, &s_40, &s_38, 
  		  NULL, &s_21, NULL, 
  		  &f_39, (cob_field *)&c_14, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_40, &s_41, &s_39, 
  		  NULL, &s_21, &f_40, 
  		  NULL, (cob_field *)&c_14, (cob_field *)&c_7, 
  		  NULL, NULL, NULL, 
  		  1, 0, 0x200000);
  cob_set_screen (&s_41, &s_42, &s_40, 
  		  NULL, &s_21, NULL, 
  		  &f_41, (cob_field *)&c_15, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_42, &s_43, &s_41, 
  		  NULL, &s_21, &f_42, 
  		  NULL, (cob_field *)&c_15, (cob_field *)&c_7, 
  		  NULL, NULL, NULL, 
  		  1, 0, 0x200000);
  cob_set_screen (&s_43, &s_44, &s_42, 
  		  NULL, &s_21, NULL, 
  		  &f_43, (cob_field *)&c_16, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_44, &s_45, &s_43, 
  		  NULL, &s_21, &f_44, 
  		  NULL, (cob_field *)&c_16, (cob_field *)&c_7, 
  		  NULL, NULL, NULL, 
  		  1, 0, 0x200000);
  cob_set_screen (&s_45, &s_46, &s_44, 
  		  NULL, &s_21, NULL, 
  		  &f_45, (cob_field *)&c_17, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_46, &s_47, &s_45, 
  		  NULL, &s_21, &f_46, 
  		  NULL, (cob_field *)&c_17, (cob_field *)&c_7, 
  		  NULL, NULL, NULL, 
  		  1, 0, 0x200000);
  cob_set_screen (&s_47, &s_48, &s_46, 
  		  NULL, &s_21, NULL, 
  		  &f_47, (cob_field *)&c_18, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_48, &s_49, &s_47, 
  		  NULL, &s_21, &f_48, 
  		  NULL, (cob_field *)&c_18, (cob_field *)&c_7, 
  		  NULL, NULL, NULL, 
  		  1, 0, 0x200000);
  cob_set_screen (&s_49, &s_50, &s_48, 
  		  NULL, &s_21, NULL, 
  		  &f_49, (cob_field *)&c_19, (cob_field *)&c_5, 
  		  NULL, NULL, NULL, 
  		  2, 0, 0x0);
  cob_set_screen (&s_50, NULL, &s_49, 
  		  NULL, &s_21, &f_50, 
  		  NULL, (cob_field *)&c_19, (cob_field *)&c_7, 
  		  NULL, NULL, NULL, 
  		  1, 0, 0x200000);

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  initialized = 0;
  return 0;

}

/* End PROGRAM-ID 'money_counter' */

/* End functions */

